In [38]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [39]:
# this is a 2D array

array_2d = np.array([[1,2,3,4],[5,6,7,8]])

# this is 3D array 

array_3d = np.array([[[1,2,3],[5,6,7]],[[9,0,0],[5,2,0]]])

# this gives u the dimensions of the array 

print(array_2d.ndim)
print(array_3d.ndim)

higher_dim = np.array([1,2,3,4], ndmin=5)

print("high dim array",higher_dim)

2
3
high dim array [[[[[1 2 3 4]]]]]


In [40]:
# time to slice 

array = np.array([1,2,3,4])

print(array[0] + array[2])

# slicing above 2d array

print(array_2d[1,1])
print(array_3d[0,1,2])


4
6
7


In [41]:
# Done until array slicing 
# data types aint shit soo going to the next one

In [42]:
# Copy vs View

# 1. Copy creats a whole new array with its own data and any changes to this array will not effect the original array
# 2. View doesnt create a new array, instad it refers to the same original data and any changes made to this array will change the original array


# copy example 

copy_array = np.array([1,3,5,6])
x =  copy_array.copy()

# edit the first one
copy_array[0] = 10

print("copy array",copy_array)
print("x array",x)


# now do the exampel on view


view_array = np.array([1,2,3,4,5])
v = view_array.view()

view_array[0] = 100
print(view_array)
print(v)


copy array [10  3  5  6]
x array [1 3 5 6]
[100   2   3   4   5]
[100   2   3   4   5]


In [43]:
# get the shape of an array  using .shape 

array_2D = np.array([[2,3,4,5],[1,2,2,3]])
print(array_2D.shape)


# reshape converts specific dimention array into higher or lower dimension array

regular_array = np.array([1,1,3,3,4,5,6,7,7,8,8,9])
print(regular_array.reshape(4,3))
print("higher 1d to 3d reshaping below------------------------------------")
print(regular_array.reshape(2,3,2))

(2, 4)
[[1 1 3]
 [3 4 5]
 [6 7 7]
 [8 8 9]]
higher 1d to 3d reshaping below------------------------------------
[[[1 1]
  [3 3]
  [4 5]]

 [[6 7]
  [7 8]
  [8 9]]]


In [49]:
# iterating throught array using for loop


array1d = np.array([1,2,3,4,5])

for x in array1d:
    print(x)
    
print("gap between 1d and 2d array---------------")
    
array2d = np.array([[1,2,3,4,5],[7,8,9,0,10]])
for i in array2d:
    for y in i:
        print(y)
    # print(i)
    
    
    print("gap for 3D-------------------")
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

for x in array3d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
gap between 1d and 2d array---------------
1
2
3
4
5
gap for 3D-------------------
7
8
9
0
10
gap for 3D-------------------
1
2
3
4
5
6
7
8
9
